<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * @file
 * Primary module hooks for SAML Authentication multi IDP module.
 */

/**
 * Implements hook_form_FORM_ID_alter() to remove some stuff no longer being used.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @return void
 */
function samlauth_multi_idp_form_samlauth_configure_form_alter(array &$form, FormStateInterface $form_state)
{

  /**
   * Replaces the original 'identity provider' details panel with a new one
   * giving some context and a link to where the identity providers are now
   * configured.
   */
  if (array_key_exists('identity_provider', $form)) {
    $form['identity_provider'] = [
      '#type' => 'details',
      '#title' => t('Identity Provider'),
      '#open' => TRUE,
    ];

    $form['identity_provider']['description'] = [
      '#type' => 'markup',
      '#markup' => '<p><em>' . t('<a href="@link">Identity provider</a> settings have been moved to a dedicated page to support multiple identity providers.', [
          '@link' =>
            Url::fromRoute('entity.samlauth_idp.collection')
              ->toString()
        ]) . '</em></p>',
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter() to generate login links for the configured identity providers.
 */
function samlauth_multi_idp_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $idps = \Drupal::entityTypeManager()->getStorage('samlauth_idp')->loadByProperties([
    'login_link_enabled' => TRUE,
  ]);

  $form['saml_login_links'] = [
    '#type' => 'container',
  ];

  foreach ($idps as $idp) {
    $form['saml_login_links'][] = [
      '#prefix' => '<p>',
      '#suffix' => '</p>',
      '#type' => 'link',
      '#title' => $idp->get('login_link_text'),
      '#url' => Url::fromRoute('samlauth.saml_controller_login', [], [
        'query' => [
          'saml_idp' => $idp->id(),
        ],
      ]),
    ];
  }
}

/**
 * Implements hook_theme() to create a template for the custom route
 */
function samlauth_multi_idp_theme($existing, $type, $theme, $path) {
  return [
    'samlauth_idp_login' => [
      'template' => 'samlauth_idp_login',
      'variables' => [
        'content' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_alter().
 * This hook forces the SamlauthIdp entity to use the custom storage class we provided.
 *
 * (HINT: This was due to an issue with the storage declaration in the entity class not
 * being picked up correctly)
 */
function samlauth_multi_idp_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['samlauth_idp'])) {
    $entity_types['samlauth_idp']->setStorageClass('Drupal\samlauth_multi_idp\SamlauthIdpStorage');
  }
}
